feat: allows to define a prefix for collections / tables
gravitee-io/gravitee-repository-jdbc pull request #142
Opened 2021-02-24 10:33 UTC by ytvnr

Fixes gravitee-io/issues#4715

- [ ] Test container
  - [ ] postgresql-tc
  - [ ] mysql-tc
  - [ ] mariadb-tc
  - [ ] sqlserver-tc
- [ ] Test embedded
   - [ ] postgresql-te  
   - [ ] mysql-te
   - [ ] mariadb-te
 - [ ] Postman
    - [ ] JDBC
    - [ ] Mongo

2021-03-01 15:37 UTC, phiz71 requested changes
On top of the review comments, I think you should replace all `getTableNameFor("xxx")` with instance variables, initialized in the constructor.

2021-03-01 15:37 UTC, phiz71 commented on src/main/java/io/gravitee/repository/jdbc/management/JdbcAlertRepository.java
> +        SELECT_ESCAPED_ALERT_TRIGGERS_TABLE_NAME = "select * from " + escapeReservedWord(this.tableName);
Does 'alert_triggers' need to be escaped ?

2021-03-01 15:37 UTC, phiz71 commented on src/main/java/io/gravitee/repository/jdbc/management/JdbcApiKeyRepository.java
> +            List<ApiKey> apiKeys = jdbcTemplate.query("select * from " + escapeReservedWord(this.tableName) + " where subscription = ?"
escape the table name in the constructor
```suggestion
            List<ApiKey> apiKeys = jdbcTemplate.query(getOrm().getSelectAllSql() + " where subscription = ?"

```

2021-03-01 15:37 UTC, phiz71 commented on src/main/java/io/gravitee/repository/jdbc/management/JdbcApiKeyRepository.java
> +            List<ApiKey> items = jdbcTemplate.query("select * from " + escapeReservedWord(this.tableName) + " where plan = ?"
escape the table name in the constructor
```suggestion
            List<ApiKey> items = jdbcTemplate.query(getOrm().getSelectAllSql() + " where plan = ?"

```

2021-03-01 15:37 UTC, phiz71 commented on src/main/java/io/gravitee/repository/jdbc/management/JdbcCommandRepository.java
> +            jdbcTemplate.query("select * from " + escapeReservedWord(this.tableName) + " c " +
escape table name in the constructor
```suggestion
            jdbcTemplate.query(getOrm().getSelectAllSql() + " c " +
```

2021-03-01 15:37 UTC, phiz71 commented on src/main/java/io/gravitee/repository/jdbc/management/JdbcCommandRepository.java
> +                "select * from " + escapeReservedWord(this.tableName) + " c " +
escape the table name in the constructor
```suggestion
                getOrm().getSelectAll() + " c " +
```

2021-03-01 15:37 UTC, phiz71 commented on src/main/java/io/gravitee/repository/jdbc/management/JdbcParameterRepository.java
> +            final List<Parameter> items = jdbcTemplate.query(getOrm().getSelectAllSql() + " where " + escapeReservedWord("key") + " = ? and reference_type = ? and reference_id = ?"
getSelectAll() escapes the table name.
```suggestion
            final List<Parameter> items = jdbcTemplate.query("select * from " + this.tableName + " where " + escapeReservedWord("key") + " = ? and reference_type = ? and reference_id = ?"

```

2021-03-01 15:37 UTC, phiz71 commented on src/main/java/io/gravitee/repository/jdbc/management/JdbcParameterRepository.java
> +            List<Parameter> parameters = jdbcTemplate.query(getOrm().getSelectAllSql() + " where reference_id = ? and reference_type = ? and " + escapeReservedWord("key") + " in ( "
getSelectAll() escapes the table name.

```suggestion
            List<Parameter> parameters = jdbcTemplate.query("select * from " + this.tableName + " where reference_id = ? and reference_type = ? and " + escapeReservedWord("key") + " in ( "

```

2021-03-01 15:37 UTC, phiz71 commented on src/main/java/io/gravitee/repository/jdbc/management/JdbcParameterRepository.java
> +            List<Parameter> parameters = jdbcTemplate.query(getOrm().getSelectAllSql() + " where reference_id = ? and reference_type = ?"
getSelectAll() escapes the table name.

```suggestion
            List<Parameter> parameters = jdbcTemplate.query("select  * from " + this.tableName + " where reference_id = ? and reference_type = ?"

```

2021-03-01 15:37 UTC, phiz71 commented on src/main/java/io/gravitee/repository/jdbc/ratelimit/JdbcRateLimitRepository.java
> +        return "insert into " + getTableNameFor("ratelimit") + " (" +
Add a constructor and initialize an instance variable with the table name and the prefix

2021-03-08 12:10 UTC, ytvnr commented on src/main/java/io/gravitee/repository/jdbc/management/JdbcApiKeyRepository.java
> +            List<ApiKey> apiKeys = jdbcTemplate.query("select * from " + escapeReservedWord(this.tableName) + " where subscription = ?"
done

2021-03-08 12:27 UTC, ytvnr commented on src/main/java/io/gravitee/repository/jdbc/management/JdbcAlertRepository.java
> +        SELECT_ESCAPED_ALERT_TRIGGERS_TABLE_NAME = "select * from " + escapeReservedWord(this.tableName);
i used getSelectAll()

2021-03-09 13:59 UTC, phiz71 approved these changes

2021-03-10 08:18 UTC, merged